version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - LOG_LEVEL=DEBUG
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
