version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs/backend.log:/app/backend.log 
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    container_name: frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./logs/frontend.log:/app/frontend.log 
    networks:
      - backend_network
    environment:
      - DEBUG=true 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: postgres_dev
    env_file:
      - .env
    volumes:
      - taskflow_pgdata:/var/lib/postgresql/data
      - ./logs/postgres.log:/var/log/postgresql/postgres.log 
    ports:
      - "5432:5432"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOGGING=on
      - POSTGRES_LOG_DESTINATION=stderr
      - POSTGRES_LOG_ERROR_VERBOSITY=verbose
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  taskflow_pgdata:

networks:
  backend_network:
