"""Initial migration

Revision ID: d11288e564ef
Revises: 5d0871937eb7
Create Date: 2025-03-04 14:26:06.309701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11288e564ef'
down_revision: Union[str, None] = '5d0871937eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_projects_id', table_name='projects')
    op.create_index(op.f('ix_public_projects_id'), 'projects', ['id'], unique=False, schema='public')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.create_index(op.f('ix_public_tasks_id'), 'tasks', ['id'], unique=False, schema='public')
    op.drop_constraint('tasks_project_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_username'), 'users', ['username'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_username'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_constraint(None, 'tasks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tasks', schema='public', type_='foreignkey')
    op.create_foreign_key('tasks_project_id_fkey', 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_public_tasks_id'), table_name='tasks', schema='public')
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'projects', schema='public', type_='foreignkey')
    op.drop_index(op.f('ix_public_projects_id'), table_name='projects', schema='public')
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
